const data = {
    products: [
        {
            _id:"1",
            name: "Nikee Slimfit Shirt",
            category:"Shirts",
            image: "/images/p1.jpg",
            price: 1000,
            brand: "Nikee",
            rating: 4.5,
            numReviews: 10,
            stockCount:10,
            description: "High quality product HSDGAVFJAKJFG YUUAYSGDKANKDUI ZK UAHSFAKSH UAHSIODJAL HUI AHSODFL  UHAOSJDON HASOID OSADPO",
        },
        {
            _id:"2",
            name: "Reebok Slimfit Shirt",
            category:"Shirts",
            image: "/images/p2.jpg",
            price: 950,
            brand: "Reebok",
            rating: 3.5,
            numReviews: 8,
            stockCount:0,
            description: "Medium-High quality product e bwerbhwebrwebnwfDS DGWNRWETHWE WENWF G ",
        },
        {
            _id:"3",
            name: "Adidass Slimfit Shirt",
            category:"Shirts",
            image: "/images/p3.jpg",
            price: 1050,
            brand: "Adidass",
            rating: 5,
            numReviews: 15,
            stockCount:11,
            description: "High sdg sd€sdsgsd €sdgbwe€ fquality sd€sdg €g €sdgn aerdtgerg product",
        },
        {
            _id:"4",
            name: "Nikee Slimfit Pant",
            category:"Pants",
            image: "/images/p4.jpg",
            price: 1000,
            brand: "Nikee",
            rating: 4,
            numReviews: 11,
            stockCount:5,
            description: "High quality product sdgsdf sda sdfdgsdgsg sdgsfgs€sff sgefhyetgag ergs€sgdh ",
        },
        {
            _id:"5",
            name: "Reebok Slimfit Pant",
            category:"Pants",
            image: "/images/p5.jpg",
            price: 900,
            brand: "Reebok",
            rating: 4.5,
            numReviews: 13,
            stockCount:0,
            description: "High sdfgsdf sdf asfgearvgsfy5tyearg nquality product",
        },
        {
            _id:"6",
            name: "Adidass Slimfit Pant",
            category:"Pants",
            image: "/images/p6.jpg",
            price: 1050,
            brand: "Adidass",
            rating: 3,
            numReviews: 17,
            stockCount:14,
            description: "High quality product po€sfiogjspdf sdpogvjilsdkf'adf sdf",
        },
    ],
};
export default data;
